export type Case = { name: string; rules: string; path: string; expected?: boolean };
// expected is filled from real `git check-ignore` by verify-against-git.ts; the oracle embeds the verified values.
export const cases: Case[] = [
  { name: 'plain-name-any-depth', rules: 'foo', path: 'a/b/foo' },
  { name: 'plain-name-root', rules: 'foo', path: 'foo' },
  { name: 'plain-name-not-substring', rules: 'foo', path: 'a/foobar' },
  { name: 'star-suffix', rules: '*.log', path: 'logs/x/app.log' },
  { name: 'star-no-cross-slash', rules: 'a*b', path: 'a/x/b' },
  { name: 'anchored-leading-slash-hit', rules: '/build', path: 'build' },
  { name: 'anchored-leading-slash-miss', rules: '/build', path: 'src/build' },
  { name: 'anchored-middle-slash-hit', rules: 'doc/frotz', path: 'doc/frotz' },
  { name: 'anchored-middle-slash-miss', rules: 'doc/frotz', path: 'a/doc/frotz' },
  { name: 'dir-only-ignores-children', rules: 'build/', path: 'build/out.js' },
  { name: 'dir-only-nested-any-depth', rules: 'build/', path: 'pkg/build/out.js' },
  { name: 'dir-only-not-a-file', rules: 'build/', path: 'src/build' },
  { name: 'negate-reincludes-file', rules: '*.log\n!keep.log', path: 'keep.log' },
  { name: 'negate-order-last-wins', rules: '!keep.log\n*.log', path: 'keep.log' },
  { name: 'parent-excluded-cannot-reinclude', rules: 'build/\n!build/keep.txt', path: 'build/keep.txt' },
  { name: 'parent-excluded-star-cannot-reinclude', rules: 'out/*\n!out/keep/\nout/keep/*', path: 'out/keep/a.txt' },
  { name: 'parent-reincluded-then-child-rules', rules: 'logs/*\n!logs/keep\nlogs/keep/*.tmp', path: 'logs/keep/x.tmp' },
  { name: 'parent-reincluded-file-ok', rules: 'logs/*\n!logs/keep/', path: 'logs/keep/x.txt' },
  { name: 'double-star-leading', rules: '**/cache', path: 'a/b/cache/x' },
  { name: 'double-star-leading-root', rules: '**/cache', path: 'cache/x' },
  { name: 'double-star-middle-zero-dirs', rules: 'a/**/b', path: 'a/b' },
  { name: 'double-star-middle-many-dirs', rules: 'a/**/b', path: 'a/x/y/b' },
  { name: 'double-star-middle-miss', rules: 'a/**/b', path: 'x/a/b' },
  { name: 'double-star-trailing-inside', rules: 'abc/**', path: 'abc/d/e.txt' },
  { name: 'double-star-trailing-not-self', rules: 'abc/**', path: 'abc' },
  { name: 'question-mark', rules: 'f?o', path: 'fzo' },
  { name: 'question-mark-not-slash', rules: 'f?o', path: 'f/o' },
  { name: 'comment-line', rules: '# foo\nbar', path: 'foo' },
  { name: 'blank-lines-ignored', rules: '\n\nfoo\n\n', path: 'foo' },
  { name: 'trailing-spaces-stripped', rules: 'foo   ', path: 'foo' },
  { name: 'negate-dir-pattern', rules: '*\n!*/\n!*.ts', path: 'src/a.ts' },
  { name: 'star-then-negate-dirs-file-not-ts', rules: '*\n!*/\n!*.ts', path: 'src/a.js' },
  { name: 'anchored-dir-only', rules: '/doc/', path: 'doc/a.txt' },
  { name: 'anchored-dir-only-miss', rules: '/doc/', path: 'x/doc/a.txt' },
  { name: 'star-in-middle-of-anchored', rules: 'src/*/gen', path: 'src/a/gen' },
  { name: 'star-in-middle-of-anchored-too-deep', rules: 'src/*/gen', path: 'src/a/b/gen' },
  { name: 'ignored-file-inside-ignored-dir-by-name', rules: 'node_modules', path: 'node_modules/x/y.js' },
  { name: 'later-positive-overrides-earlier-negate', rules: '!a.txt\na.txt', path: 'a.txt' },
  { name: 'double-star-alone-inside-unanchored', rules: 'x/**/y/z', path: 'x/y/z' },
];
