export type Case = { name: string; input: string };
export const cases: Case[] = [
  { name: 'plain-words', input: 'a b c' },
  { name: 'multiple-whitespace-kinds', input: '  a \t b\nc\r\nd  ' },
  { name: 'empty-string', input: '' },
  { name: 'only-whitespace', input: ' \t\n ' },
  { name: 'single-quoted-space', input: "a 'b c' d" },
  { name: 'double-quoted-space', input: 'a "b c" d' },
  { name: 'adjacent-segments-concatenate', input: 'a"b c"d\'e f\'g' },
  { name: 'empty-single-quotes-make-empty-word', input: "a '' b" },
  { name: 'empty-double-quotes-make-empty-word', input: 'a "" b' },
  { name: 'empty-quotes-attached-to-word', input: 'a""b' },
  { name: 'unquoted-backslash-escapes-space', input: 'a\\ b c' },
  { name: 'unquoted-backslash-escapes-quote', input: 'a\\"b \\\'c' },
  { name: 'unquoted-backslash-escapes-backslash', input: 'a\\\\b' },
  { name: 'unquoted-backslash-escapes-ordinary-char', input: 'a\\bc' },
  { name: 'double-quote-backslash-quote', input: '"a\\"b"' },
  { name: 'double-quote-backslash-backslash', input: '"a\\\\b"' },
  { name: 'double-quote-backslash-ordinary-kept', input: '"a\\bc"' },
  { name: 'double-quote-backslash-dollar-kept', input: '"a\\$b"' },
  { name: 'double-quote-dollar-literal', input: '"$HOME `x`"' },
  { name: 'single-quote-backslash-literal', input: "'a\\b\\'" },
  { name: 'single-quote-holds-double-quote', input: "'a\"b'" },
  { name: 'double-quote-holds-single-quote', input: '"a\'b"' },
  { name: 'hash-is-literal', input: 'a #b c' },
  { name: 'newline-inside-quotes-kept', input: '"a\nb" c' },
  { name: 'tab-inside-quotes-kept', input: "'a\tb'" },
  { name: 'quote-adjacent-to-space', input: '"a" "b"' },
  { name: 'unicode-words', input: 'é "日本 語" ü' },
  { name: 'error-unterminated-single', input: "a 'b" },
  { name: 'error-unterminated-double', input: 'a "b' },
  { name: 'error-trailing-backslash', input: 'a b\\' },
  { name: 'error-escaped-quote-then-open', input: '"a\\"' },
];
