/**
 * Renders LaTeX tables (pasted verbatim into main.tex via \input) from paper/generated/fig-data.json
 * (itself written by scripts/paper-fig-data.ts from the committed bench/results/rq1-suite and
 * bench/results/rq1-arm-k artifacts). No statistic here is computed independently of fig-data.json —
 * this script only formats numbers that are already on disk, so a table cannot drift from the figures
 * built from the same fig-data.json by scripts/paper-fig.py.
 *
 * Usage: node --import tsx scripts/paper-fig-tables.ts [FIG_DATA_JSON] [OUT_DIR]
 *   Defaults: FIG_DATA_JSON=paper/generated/fig-data.json OUT_DIR=paper/tables
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { FigData } from "./paper-fig-data.js";

const TASK_ORDER = ["stamp-interpreter", "stamp-2", "bench-printf-format"];
const ARM_ORDER = ["A", "C", "K"];
const ARM_LABEL: Record<string, string> = { A: "A (single agent)", C: "C (chatroom)", K: "K (independent + selection)" };

function taskRank(t: string): number {
  const i = TASK_ORDER.indexOf(t);
  return i === -1 ? TASK_ORDER.length : i;
}
function armRank(a: string): number {
  const i = ARM_ORDER.indexOf(a);
  return i === -1 ? ARM_ORDER.length : i;
}
function escapeTex(s: string): string {
  return s.replace(/_/g, "\\_");
}
function fmtPct(x: number | null, digits = 1): string {
  return x === null ? "--" : `${(x * 100).toFixed(digits)}\\%`;
}
function fmtUsd(x: number | null, digits = 4): string {
  return x === null ? "undefined" : `\\$${x.toFixed(digits)}`;
}

export function renderPassRateTable(data: FigData): string {
  const rows = [...data.pass_rates].sort((a, b) => taskRank(a.task) - taskRank(b.task) || armRank(a.arm) - armRank(b.arm));
  let tex = "% Generated by scripts/paper-fig-tables.ts from paper/generated/fig-data.json. Do not hand-edit.\n";
  tex += "\\begin{table}[t]\n\\centering\n\\caption{Task success rate by arm and task, with 95\\% Wilson score intervals.}\n\\label{tab:pass-rate}\n";
  tex += "\\begin{tabular}{llrrrl}\n\\toprule\ntask & arm & $n$ & pass & rate & 95\\% CI \\\\\n\\midrule\n";
  for (const r of rows) {
    const ci = r.ci_lo === null || r.ci_hi === null ? "--" : `[${fmtPct(r.ci_lo)}, ${fmtPct(r.ci_hi)}]`;
    tex += `${escapeTex(r.task)} & ${ARM_LABEL[r.arm] ?? r.arm} & ${r.n} & ${r.pass} & ${fmtPct(r.rate)} & ${ci} \\\\\n`;
  }
  tex += "\\bottomrule\n\\end{tabular}\n\\end{table}\n";
  return tex;
}

export function renderCostTable(data: FigData): string {
  const rows = [...data.cost_per_correct].sort((a, b) => taskRank(a.task) - taskRank(b.task) || armRank(a.arm) - armRank(b.arm));
  let tex = "% Generated by scripts/paper-fig-tables.ts from paper/generated/fig-data.json. Do not hand-edit.\n";
  tex += "\\begin{table}[t]\n\\centering\n\\caption{Cost per correct answer by arm and task (API list price; arm K sums all $k$ attempts, including killed attempts).}\n\\label{tab:cost-per-correct}\n";
  tex += "\\begin{tabular}{llrr}\n\\toprule\ntask & arm & pass/$n$ & cost per correct \\\\\n\\midrule\n";
  for (const r of rows) {
    tex += `${escapeTex(r.task)} & ${ARM_LABEL[r.arm] ?? r.arm} & ${r.pass}/${r.n} & ${fmtUsd(r.cost_per_correct)} \\\\\n`;
  }
  tex += "\\bottomrule\n\\end{tabular}\n\\end{table}\n";
  return tex;
}

async function main() {
  const argv = process.argv.slice(2);
  const figDataPath = resolve(argv[0] ?? "paper/generated/fig-data.json");
  const outDir = resolve(argv[1] ?? "paper/tables");
  if (!existsSync(figDataPath)) throw Error(`missing ${figDataPath}; run scripts/paper-fig-data.ts first`);
  const data = JSON.parse(readFileSync(figDataPath, "utf8")) as FigData;
  mkdirSync(outDir, { recursive: true });
  const passRatePath = resolve(outDir, "pass-rate-table.tex");
  const costPath = resolve(outDir, "cost-per-correct-table.tex");
  writeFileSync(passRatePath, renderPassRateTable(data));
  writeFileSync(costPath, renderCostTable(data));
  console.log(`Wrote ${passRatePath}`);
  console.log(`Wrote ${costPath}`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(String(error));
    process.exitCode = 1;
  });
}
