#!/usr/bin/env bash
# One deduplicated list of every arXiv id / DOI this project has already read, with where it is cited.
# Usage: scripts/research-index.sh            (markdown to stdout)
#        scripts/research-index.sh --ids      (bare ids, one per line — for prompts)
set -euo pipefail
cd "$(dirname "$0")/.."
FILES=$(ls docs/decisions/*.md docs/*.md README.md 2>/dev/null | grep -v INDEX.md || true)
if [ "${1:-}" = "--ids" ]; then
  grep -ohE "arXiv:[a-z-]*/?[0-9]{4}\.[0-9]{4,5}|arXiv:cs/[0-9]{7}|10\.[0-9]{4,}/[^ ),;]+" $FILES | sort -u
  exit 0
fi
echo "# Research already read (auto-generated by scripts/research-index.sh)"
echo
echo "| Source | Cited in |"
echo "|---|---|"
grep -ohE "arXiv:[a-z-]*/?[0-9]{4}\.[0-9]{4,5}|arXiv:cs/[0-9]{7}|10\.[0-9]{4,}/[^ ),;]+" $FILES | sort -u | while read -r id; do
  where=$(grep -l -F "$id" $FILES | sed 's|docs/decisions/||; s|\.md$||' | sort -u | tr '\n' ' ')
  echo "| $id | $where |"
done
