export const SCENARIOS: Record<string, (W: any, m: number) => unknown> = {
  S01: (W,m)=>{const w=new W;w.receive("L1","A",5*m,100,0);const s1=w.place("o1",[{sku:"A",qty:2*m},{sku:"B",qty:1}],1);const s2=w.place("o2",[{sku:"A",qty:5*m}],1);return[s1,s2,w.snapshot(1)]},
  S02: (W,m)=>{const w=new W;w.receive("L2","A",3*m,50,0);w.receive("L1","A",3*m,50,0);w.place("o1",[{sku:"A",qty:2*m}],1);return w.snapshot(1)},
  S03: (W,m)=>{const w=new W;w.receive("L1","A",4*m,10,0);const s=w.place("o1",[{sku:"A",qty:2*m}],10);return[s,w.snapshot(10)]},
  S04: (W,m)=>{const w=new W;w.receive("L1","A",10*m,99,0);w.place("o1",[{sku:"A",qty:4*m}],1);const a=w.ship("o1","A",3*m);const b=w.ship("o1","A",3*m);return[a,b,w.snapshot(2)]},
  S05: (W,m)=>{const w=new W;w.receive("L1","A",10*m,99,0);w.place("o1",[{sku:"A",qty:6*m}],1);w.ship("o1","A",2*m);const c=w.cancel("o1",2);return[c,w.snapshot(2)]},
  S06: (W,m)=>{const w=new W;w.receive("L1","A",10*m,99,0);w.place("o1",[{sku:"A",qty:5*m}],1);w.ship("o1","A",5*m);const r=[w.returnItems("o1","A",3*m,2),w.returnItems("o1","A",2*m,2),w.returnItems("o1","A",1,2)];return[r,w.snapshot(2)]},
  S07: (W,m)=>{const w=new W;w.receive("L1","A",10*m,20,0);w.place("o1",[{sku:"A",qty:4*m}],5);w.ship("o1","A",4*m);const r=w.returnItems("o1","A",4*m,21);return[r,w.snapshot(21)]},
  S08: (W,m)=>{const w=new W;w.place("o1",[{sku:"A",qty:5*m}],0);w.place("o2",[{sku:"A",qty:1*m}],0);w.place("o3",[{sku:"A",qty:3*m}],0);w.receive("L9","A",6*m,99,1);return w.snapshot(1)},
  S09: (W,m)=>{const w=new W;w.receive("L1","A",3*m,99,0);w.place("o1",[{sku:"A",qty:3*m}],1);w.place("o2",[{sku:"A",qty:3*m}],1);w.cancel("o1",2);return w.snapshot(2)},
  S10: (W,m)=>{const w=new W;w.receive("L1","A",5*m,99,0);w.receive("L1","A",3*m,99,0);return w.snapshot(1)},
  S11: (W,m)=>{const w=new W;w.receive("L1","A",5*m,10,0);w.receive("L2","A",2*m,30,0);return[w.snapshot(11),w.snapshot(10)]},
  S12: (W,m)=>{const w=new W;w.place("o1",[{sku:"A",qty:2*m}],0);w.cancel("o1",0);w.receive("L1","A",5*m,99,1);return w.snapshot(1)},
  R01: (W,m)=>{const w=new W;w.receive("L1","A",10*m,99,0);w.receive("L2","B",4*m,99,0);const s=w.place("o1",[{sku:"A",qty:3*m},{sku:"B",qty:2*m}],1);return[s,w.snapshot(1)]},
  R02: (W,m)=>{const w=new W;w.receive("L1","A",3*m,40,0);w.receive("L2","A",3*m,30,0);w.place("o1",[{sku:"A",qty:4*m}],1);return w.snapshot(1)},
  R03: (W,m)=>{const w=new W;w.receive("L1","A",10*m,99,0);w.place("o1",[{sku:"A",qty:4*m}],1);const a=w.ship("o1","A",1*m);const b=w.ship("o1","A",9*m);const c=w.ship("o1","A",3*m);return[a,b,c]},
  R04: (W,m)=>{const w=new W;w.receive("L1","A",4*m,99,0);w.place("o1",[{sku:"A",qty:4*m}],1);w.place("o2",[{sku:"A",qty:2*m}],1);w.receive("L2","A",5*m,99,2);return w.snapshot(2)},
  R05: (W,m)=>{const w=new W;w.receive("L1","A",8*m,99,0);w.place("o1",[{sku:"A",qty:4*m}],1);const c1=w.cancel("o1",2);const c2=w.cancel("o1",2);const c3=w.cancel("nope",2);return[c1,c2,c3,w.snapshot(2)]},
  R06: (W,m)=>{const w=new W;w.receive("L1","A",8*m,99,0);w.place("o1",[{sku:"A",qty:4*m}],1);w.ship("o1","A",4*m);const r=w.returnItems("o1","A",2*m,2);const bad=w.returnItems("o1","A",0,2);const bad2=w.returnItems("zz","A",1,2);return[r,bad,bad2,w.snapshot(2)]},
  R07: (W,m)=>{const w=new W;w.receive("L1","A",2*m,99,0);w.place("o1",[{sku:"A",qty:5*m}],1);w.place("o2",[{sku:"A",qty:1*m}],1);return w.snapshot(1)},
  R08: (W,m)=>{const w=new W;w.receive("L1","A",6*m,99,0);w.receive("L2","A",6*m,120,0);w.place("o1",[{sku:"A",qty:8*m}],3);w.ship("o1","A",8*m);w.returnItems("o1","A",3*m,4);return w.snapshot(4)},
};
